export default [{
		"path": "",
		"displayOrdinal": 6,
		"children": [{
			"path": "/sentiment/overview",
			"displayOrdinal": 11,
			"pid": "YUQINGGUANLI",
			"id": "YQZL",
			"title": "媒体舆情总览",
			"nodeId": "YQZL",
			"hasLeaf": false,
			"iconClass": "",
			"parentId": "YUQINGGUANLI",
			"createDateTime": 1528953481000
		}, {
			"path": "/sentiment/MediaSentiment",
			"displayOrdinal": 12,
			"pid": "YUQINGGUANLI",
			"id": "M_MEDIASENTIMENT",
			"title": "媒体舆情监测",
			"nodeId": "M_MEDIASENTIMENT",
			"hasLeaf": false,
			"iconClass": "",
			"parentId": "YUQINGGUANLI",
			"createDateTime": 1538792175000
		}, {
			"path": "/sentiment/sentimentsearch",
			"displayOrdinal": 12,
			"pid": "YUQINGGUANLI",
			"id": "YSS",
			"title": "云搜索",
			"nodeId": "YSS",
			"hasLeaf": false,
			"iconClass": "",
			"parentId": "YUQINGGUANLI",
			"createDateTime": 1528953510000
		}],
		"pid": "",
		"id": "YUQINGGUANLI",
		"title": "媒体舆情",
		"nodeId": "YUQINGGUANLI",
		"hasLeaf": true,
		"iconClass": "icon-shijianjiance",
		"parentId": "",
		"createDateTime": 1528348645000
	}, {
		"path": "",
		"displayOrdinal": 7,
		"children": [{
			"path": "/sentiment/UserSentiment",
			"displayOrdinal": 0,
			"pid": "MD_USERSENTIMENT",
			"id": "M_USERSENTIMENT",
			"title": "用户舆情总览",
			"nodeId": "M_USERSENTIMENT",
			"hasLeaf": false,
			"iconClass": "",
			"parentId": "MD_USERSENTIMENT",
			"createDateTime": 1538791624000
		}],
		"pid": "",
		"id": "MD_USERSENTIMENT",
		"title": "用户舆情",
		"nodeId": "MD_USERSENTIMENT",
		"hasLeaf": true,
		"iconClass": "icon-yujing",
		"parentId": "",
		"createDateTime": 1538791589000
	}]